server:
  port: ${app.port:9980}

spring:
  output:
    ansi:
      enabled: always
  application:
    name: gestion-transaccion
  profiles:
    active: ${environment.profile}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_ADDRESS}